CREATE DATABASE IF NOT EXISTS Co2;

CREATE USER IF NOT EXISTS 'Appuser'@'localhost' IDENTIFIED BY 'User123';

GRANT SELECT, UPDATE, INSERT, DELETE ON Co2.* TO 'Appuser'@'localhost';

FLUSH PRIVILEGES;
